import type { Metadata } from "next";
import AdminSidebar from "./_components/admin-sidebar/sidebar";
import AdminMobileNavbar from "./_components/admin-navbar/mobile-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-full">
      <div className=" h-[80px] lg:pl-56 fixed inset-y-0 w-full z-50">
        <AdminMobileNavbar />
      </div>
      <div className="hidden lg:flex h-full w-56 flex-col inset-y-0 left-0 z-50 fixed">
        <AdminSidebar />
      </div>
      <div className=" pt-[80px] lg:ml-56 h-full">{children}</div>
    </div>
  );
}
